

<footer>
    <div class='logo-container'>
        <img src="http://thrillx-test.local/wp-content/uploads/2025/01/ThrillXlogo.png" alt="ThrillX Logo" />
        <div class='socials-container'>
            <a href="/">
                <img src='/wp-content/themes/thrillx/resources/icons/ig.svg' />
            </a>
            <a href="/">
                <img src='/wp-content/themes/thrillx/resources/icons/fb.svg' />
            </a>
            <a href="/">
                <img src='/wp-content/themes/thrillx/resources/icons/in.svg' />
            </a>
        </div>
    </div>
    <div class='options-container'>
        <a href="/">ThrillX</a>
        <a href="/">Services</a>
        <a href="/">About Us</a>
        <a href="/">Careers</a>
    </div>
    <div class='others-container'>
        <a href='/'>Others</a>
        <a href="/">Contact Us</a>
    </div>
</footer>
<!-- wp_footer(); is here to load all of the dynamic scripts generated by Wordpress near the end of the body and load the admin bar whenever the admin is logged in. -->
<? wp_footer();?>
</body>
</html>