
<!-- wp_footer(); is here to load all of the dynamic scripts generated by Wordpress near the end of the body and load the admin bar whenever the admin is logged in. -->
<? wp_footer();?>
</body>
</html>