<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Assessment | ThrillX</title>

    <!-- wp_head(); is here to load all of the dynamic metadata generated by Wordpress in the head tag of the html page and load the admin bar whenever the admin is logged in. -->
    <? wp_head();?>
</head>
<body <? body_class();?> >
    <header>
        <div class='desktop-banner-container'>
            <div class='left-options'>
                <button>Residential</button>
                <a href="/">Business</a>
                <a href="/">Careers</a>
            </div>
            <div class='right-options'>
                <a href="/">Learn More</a>
                <a href="/">About Us</a>
            </div>
        </div>
        <div class='mobile-banner-container'>
            <div class='left-options'>
                <button>Residential</button>
                <a href="/">Business</a>
            </div>
            <div class='right-options'>
                <button href="/">1-888-477-2177</button>
            </div>
        </div>
    </header>