<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Assessment | ThrillX</title>

    <!-- wp_head(); is here to load all of the dynamic metadata generated by Wordpress in the head tag of the html page and load the admin bar whenever the admin is logged in. -->
    <? wp_head();?>
</head>
<body <? body_class();?> >
    <header></header>